#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "FaustDSP.h"

// Faust-generated DSP uses MapUI for name-based parameter access.
// FaustDSP.h is generated by: faust -i -a faustMinimal.h Source/effect.dsp -o Source/FaustDSP.h
// This happens in the GitHub Actions build step before CMake runs.

// ==============================================================================
// Parameter Layout - Auto-discovered from Faust DSP at runtime
// ==============================================================================

juce::AudioProcessorValueTreeState::ParameterLayout
CharmAudioProcessor::createParameterLayout()
{
    juce::AudioProcessorValueTreeState::ParameterLayout layout;

    // Parameters are auto-discovered from the Faust DSP at runtime.
    // The Faust hslider declarations define all parameters.
    // We create JUCE parameters by inspecting the Faust UI metadata.
    auto tempDsp = std::make_unique<mydsp>();
    MapUI tempUI;
    tempDsp->buildUserInterface(&tempUI);

    // MapUI::getMap() returns std::map<std::string, FAUSTFLOAT*>
    // Keys are full paths like "/effect/Size", values are zone pointers.
    for (const auto& [path, zone] : tempUI.getMap()) {
        // Extract short name from path (e.g., "/effect/Size" -> "Size")
        auto shortName = path.substr(path.rfind('/') + 1);
        auto paramId = juce::String(shortName).toUpperCase().replaceCharacter(' ', '_');

        // Read current value from the zone pointer (this is the Faust default)
        float defaultVal = *zone;

        // For parameter discovery, use full 0-1 range (Faust handles the mapping internally)
        float minVal = 0.0f, maxVal = 1.0f, step = 0.01f;
        layout.add(std::make_unique<juce::AudioParameterFloat>(
            juce::ParameterID { paramId, 1 },
            shortName,
            juce::NormalisableRange<float>(minVal, maxVal, step),
            defaultVal
        ));
    }

    return layout;
}

// ==============================================================================
// Constructor
// ==============================================================================

CharmAudioProcessor::CharmAudioProcessor()
    : AudioProcessor(BusesProperties()
                        .withInput("Input", juce::AudioChannelSet::stereo(), true)
                        .withOutput("Output", juce::AudioChannelSet::stereo(), true))
    , parameters(*this, nullptr, "Parameters", createParameterLayout())
{
}

CharmAudioProcessor::~CharmAudioProcessor()
{
}

// ==============================================================================
// Prepare to Play - Called before playback starts
// ==============================================================================

void CharmAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
    juce::ignoreUnused(samplesPerBlock);

    fDSP = std::make_unique<mydsp>();
    fDSP->init(static_cast<int>(sampleRate));
    fUI = std::make_unique<MapUI>();
    fDSP->buildUserInterface(fUI.get());
}

// ==============================================================================
// Release Resources - Called when playback stops
// ==============================================================================

void CharmAudioProcessor::releaseResources()
{
    fDSP.reset();
    fUI.reset();
}

// ==============================================================================
// Process Block - Main DSP processing (called on audio thread)
// ==============================================================================

void CharmAudioProcessor::processBlock(juce::AudioBuffer<float>& buffer,
                                                  juce::MidiBuffer& midiMessages)
{
    if (!fDSP || !fUI) return;

    juce::ScopedNoDenormals noDenormals;
    juce::ignoreUnused(midiMessages);

    // Forward JUCE parameters to Faust via MapUI
    // MapUI::getMap() returns std::map<std::string, FAUSTFLOAT*>
    for (const auto& [path, zone] : fUI->getMap()) {
        auto shortName = path.substr(path.rfind('/') + 1);
        auto paramId = juce::String(shortName).toUpperCase().replaceCharacter(' ', '_');
        if (auto* param = parameters.getRawParameterValue(paramId)) {
            // Write directly to the zone pointer — this is how MapUI works
            *zone = param->load();
        }
    }

    // Faust compute — processes audio in-place
    int numSamples = buffer.getNumSamples();
    int numChannels = std::min(buffer.getNumChannels(), 2);

    float* channels[2] = { nullptr, nullptr };
    for (int ch = 0; ch < numChannels; ++ch)
        channels[ch] = buffer.getWritePointer(ch);

    // If mono input, duplicate to stereo for Faust (expects 2-channel)
    if (numChannels == 1)
        channels[1] = channels[0];

    fDSP->compute(numSamples, channels, channels);
}

// ==============================================================================
// Create Editor - Returns the plugin's GUI
// ==============================================================================

juce::AudioProcessorEditor* CharmAudioProcessor::createEditor()
{
    return new CharmAudioProcessorEditor(*this);
}

// ==============================================================================
// State Management - Save/Load plugin state (presets, DAW recall)
// ==============================================================================

void CharmAudioProcessor::getStateInformation(juce::MemoryBlock& destData)
{
    auto state = parameters.copyState();
    std::unique_ptr<juce::XmlElement> xml(state.createXml());
    copyXmlToBinary(*xml, destData);
}

void CharmAudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
    std::unique_ptr<juce::XmlElement> xmlState(getXmlFromBinary(data, sizeInBytes));

    if (xmlState != nullptr && xmlState->hasTagName(parameters.state.getType()))
        parameters.replaceState(juce::ValueTree::fromXml(*xmlState));
}

// ==============================================================================
// Factory Function - Required by JUCE plugin system
// ==============================================================================

juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new CharmAudioProcessor();
}
