#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <juce_dsp/juce_dsp.h>
#include <memory>

// FaustDSP.h is generated by: faust -i -a faustMinimal.h Source/effect.dsp -o Source/FaustDSP.h
// faustMinimal.h inlines MapUI so no separate include is needed.
#include "FaustDSP.h"

// ==============================================================================
// Satin2AudioProcessor
// ==============================================================================
// Main audio processor class. Handles Faust DSP and parameter management.
// Parameters are auto-discovered from the Faust DSP via MapUI at runtime.
// ==============================================================================

class Satin2AudioProcessor : public juce::AudioProcessor
{
public:
    Satin2AudioProcessor();
    ~Satin2AudioProcessor() override;

    // --------------------------------------------------------------------------
    // AudioProcessor Interface (Required - DO NOT MODIFY SIGNATURES)
    // --------------------------------------------------------------------------
    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;
    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return "Satin2"; }
    bool acceptsMidi() const override { return false; }
    bool producesMidi() const override { return false; }
    bool isMidiEffect() const override { return false; }
    // NOTE: For reverb/delay effects, override this to return a realistic tail time
    // (e.g., 10.0-20.0 seconds). Returning 0.0 tells the DAW to cut processing
    // immediately when input stops, which kills reverb/delay tails.
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram(int) override {}
    const juce::String getProgramName(int) override { return {}; }
    void changeProgramName(int, const juce::String&) override {}

    void getStateInformation(juce::MemoryBlock& destData) override;
    void setStateInformation(const void* data, int sizeInBytes) override;

    // --------------------------------------------------------------------------
    // Parameter Access (for Editor)
    // --------------------------------------------------------------------------
    juce::AudioProcessorValueTreeState parameters;

private:
    // --------------------------------------------------------------------------
    // Parameter Layout - Auto-discovered from Faust DSP via MapUI
    // --------------------------------------------------------------------------
    static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

    // --------------------------------------------------------------------------
    // Faust DSP members
    // fDSP: Faust-generated mydsp class (from FaustDSP.h)
    // fUI: MapUI for name-based parameter access (via MapUI::getMap())
    // --------------------------------------------------------------------------
    std::unique_ptr<dsp> fDSP;
    std::unique_ptr<MapUI> fUI;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(Satin2AudioProcessor)
};
