#include "PluginEditor.h"
#include "BinaryData.h"

// JS shim injected after HTML loads — wires [data-param] elements to JUCE WebSliderRelay.
// This makes the same HTML work in browser (Faust bridge.ts) and DAW (JUCE relay).
static const char* dataParamBridgeJS = R"JS(
(function() {
    if (!window.__JUCE__) return;

    document.querySelectorAll('[data-param]').forEach(function(el) {
        var name = el.getAttribute('data-param');
        var state = window.__JUCE__.getSliderState(name);
        if (!state) return;

        // UI knob → DAW parameter
        el.addEventListener('input', function() {
            state.setNormalisedValue(parseFloat(el.value));
        });

        // DAW automation → UI knob
        state.valueChangedEvent.addListener(function() {
            el.value = state.getNormalisedValue();
        });

        // Set initial value from DAW parameter
        el.value = state.getNormalisedValue();
    });
})();
)JS";

PluginEditor::PluginEditor (PluginProcessor& p)
    : AudioProcessorEditor (p), processorRef (p)
{
    // Step 1: Create WebSliderRelay for each parameter (BEFORE WebBrowserComponent)
    auto& apvts = processorRef.getAPVTS();
    auto& params = processorRef.getParameters();

    for (auto* param : params)
    {
        if (auto* rangedParam = dynamic_cast<juce::RangedAudioParameter*> (param))
        {
            auto label = rangedParam->getName (256);
            sliderRelays.push_back (std::make_unique<juce::WebSliderRelay> (label));
        }
    }

    // Step 2: Build WebBrowserComponent options with all relays connected
    auto options = juce::WebBrowserComponent::Options{}
        .withNativeIntegrationEnabled()
        .withResourceProvider (resourceProvider);

    for (auto& relay : sliderRelays)
        options = options.withOptionsFrom (*relay);

    // Step 3: Create WebBrowserComponent with assembled options
    webBrowser = std::make_unique<juce::WebBrowserComponent> (options);
    addAndMakeVisible (*webBrowser);

    // Step 4: Create attachments (bidirectional sync: JUCE param ↔ relay)
    int relayIndex = 0;
    for (auto* param : params)
    {
        if (auto* rangedParam = dynamic_cast<juce::RangedAudioParameter*> (param))
        {
            if (relayIndex < static_cast<int> (sliderRelays.size()))
            {
                sliderAttachments.push_back (
                    std::make_unique<juce::WebSliderParameterAttachment> (
                        *rangedParam, *sliderRelays[static_cast<size_t> (relayIndex)], nullptr
                    )
                );
                relayIndex++;
            }
        }
    }

    // Step 5: Navigate to the HTML entry point
    webBrowser->goToURL (juce::WebBrowserComponent::getResourceProviderRoot() + "/index.html");

    setSize (800, 540);
    setResizable (false, false);
}

PluginEditor::~PluginEditor() {}

void PluginEditor::resized()
{
    if (webBrowser)
        webBrowser->setBounds (getLocalBounds());
}

std::optional<juce::WebBrowserComponent::Resource>
    PluginEditor::resourceProvider (const juce::String& url)
{
    // Map URL paths to BinaryData entries
    struct BinaryFile {
        const char* urlPath;
        const char* data;
        int size;
        const char* mimeType;
    };

    // Build a lookup table from BinaryData
    // BinaryData is generated by juce_add_binary_data at compile time
    static const BinaryFile files[] = {
        { "/index.html",  BinaryData::index_html,  BinaryData::index_htmlSize,  "text/html" },
#ifdef BinaryData_styles_css
        { "/styles.css",  BinaryData::styles_css,  BinaryData::styles_cssSize,  "text/css" },
#endif
    };

    auto path = url;
    if (path == "/" || path.isEmpty())
        path = "/index.html";

    for (const auto& file : files)
    {
        if (path == file.urlPath)
        {
            // Inject the data-param bridge JS shim before </body> for HTML files
            if (juce::String (file.mimeType) == "text/html")
            {
                auto html = juce::String::fromUTF8 (file.data, file.size);
                auto shimScript = juce::String ("<script>") + dataParamBridgeJS + "</script>";

                // Insert before </body> if present, otherwise append
                if (html.contains ("</body>"))
                    html = html.replace ("</body>", shimScript + "\n</body>");
                else
                    html += shimScript;

                auto utf8 = html.toUTF8();
                return juce::WebBrowserComponent::Resource {
                    std::vector<std::byte> (
                        reinterpret_cast<const std::byte*> (utf8.getAddress()),
                        reinterpret_cast<const std::byte*> (utf8.getAddress()) + utf8.sizeInBytes() - 1
                    ),
                    "text/html"
                };
            }

            return juce::WebBrowserComponent::Resource {
                std::vector<std::byte> (
                    reinterpret_cast<const std::byte*> (file.data),
                    reinterpret_cast<const std::byte*> (file.data) + file.size
                ),
                file.mimeType
            };
        }
    }

    return std::nullopt;
}
